# Generated by Django 6.0.5 on 2026-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
