# Generated by Django 6.0.5 on 2026-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_assigned_to_workorder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
